### ISSUE TITLE
Mac环境下运行总是出错

### ISSUE THREAD

**Issue by lucifnce** [jiangph1001/gaodun_download#2]
您好！ 我在mac下运行了该程序也按照提示操作了，但是不知道为什么总是提示出错！
另外，您github的那2个图片好像也无法观看！
能否写一份使用说明呢？
谢谢~~

**Comment by jiangph1001** [comment]
readme即使用说明，没有精力去写更多的，你要是遇到问题请贴出来你的报错
图片不能看是因为我的图床暂时挂了，还没去修复，不过图片不重要，就是一个示意图而已。
